DECLARE @VAL NVARCHAR(200)
DECLARE MY_CURSOR CURSOR LOCAL STATIC READ_ONLY FORWARD_ONLY FOR
SELECT ORDER_NUM FROM TRANSPORTQUARANTINECERT
OPEN MY_CURSOR
FETCH FROM MY_CURSOR INTO @VAL
WHILE @@FETCH_STATUS = 0
    BEGIN

        FETCH FROM MY_CURSOR INTO @VAL
    END
CLOSE MY_CURSOR
DEALLOCATE MY_CURSOR
