SELECT SUM(SINGLEPAGE_KB)+SUM(MULTIPAGE_KB) FROM
(
SELECT SUM(SINGLE_PAGES_KB) AS SINGLEPAGE_KB,
    SUM(MULTI_PAGES_KB) AS MULTIPAGE_KB
FROM SYS.DM_OS_MEMORY_CLERKS
    GROUP BY TYPE
) AS A

UNION
SELECT COUNT(ROW_COUNT) * 8.0 FROM SYS.DM_OS_BUFFER_DESCRIPTORS

SELECT
    ISNULL(DB_NAME(DATABASE_ID),'RESOURCEDB') AS DATABASENAME
    , CAST(COUNT(ROW_COUNT) * 8.0 / (1024.0) AS DECIMAL(28,2))
                                                AS [SIZE (MB)]
FROM SYS.DM_OS_BUFFER_DESCRIPTORS
GROUP BY DATABASE_ID
ORDER BY DATABASENAME
